### ISSUE TITLE
language sections are not properly exported - like in MultiplyChannels_2.1.2

### ISSUE THREAD

**Issue by loevo** [OpenKNX/OpenKNXproducer#1]
language sections are not properly exported - like in MultiplyChannels_2.1.2

The attached sample works in MultiplyChannels_2.1.2, but in OpenKNXproducer_1.1.1 all language sections are added to all *.xml files.

The language section of the catalog and the language section of the application are added to all xml files - even the Hardware.xml includes both language sections.

Maybe you can have a look at the attached sample: 
[Sensor.zip](https://github.com/OpenKNX/OpenKNXproducer/files/8631670/Sensor.zip)

**Comment by loevo** [comment]
I also tested MultiplyChannels_3.2.1 which still behaves like MultiplyChannels_2.1.2.

MultiplyChannels_3.5.0 already behaves like OpenKNXproducer_1.1.1 regarding the language sections.

**Comment by mumpf** [comment]
Hi, 

tanks for your tests. The extensions for the new signing method introduced with ETS 5.7 and necessary for ETS 6.0 and which cause your problem were not programmed by me. I have first to look into and understand it. 

You have to be patient, this will take a while because I am very busy at the moment. Give me 2 or 3 weeks before there will be some progress here, sorry...

Regards,
Waldemar

**Comment by loevo** [comment]
Okay, thank you for the quick response. I will keep using MultiplyChannels 2.1.2 or 3.2.1 for the meantime.

**Comment by thewhobox** [comment]
How about:
```XML

      <Languages>
        <Language Identifier="en-US">
          <!--Catalog-->
          <TranslationUnit RefId="M-00FA_H-567-1_HP-0000-00-0000_CI-567-1">
            <TranslationElement RefId="M-00FA_H-567-1_HP-0000-00-0000_CI-567-1">
              <Translation AttributeName="Name" Text="Catalog TranslatedTempSensor" />
            </TranslationElement>
          </TranslationUnit>
        </Language>
        <Language Identifier="en-US">
          <!--Application-->
          <TranslationUnit RefId="M-00FA_A-0000-00-0000">
            <TranslationElement RefId="M-00FA_A-0000-00-0000">
              <Translation AttributeName="Name" Text="ApplicationPrograms TranslatedTempSensor" />
            </TranslationElement>
          </TranslationUnit>
        </Language>
      </Languages>
```

**Comment by mumpf** [comment]
Hi, 

OpenKNXproducer 1.5.9 now supports language sections. And the comments above are not necessary. 

Regards,
Waldemar
