### ISSUE TITLE
uctChannelParams: Default Value is Supressed when `%` is included 

### ISSUE THREAD

**Issue by cornelius-koepp** [OpenKNX/OpenKNXproducer#15]
Default-Werte werden nicht nur für Platzhalter unterdrückt, sondern sobald ein "%" enthalten ist.
Siehe auch https://github.com/OpenKNX/OFM-ConfigTransfer/issues/21

# Beispiel
Parameter `TextClouds` mit Standard-Wert `Wolken XXX%` in  [OFM-InternetWeatherModule](https://github.com/OpenKNX/OFM-InternetWeatherModule)
erzeugt:

```
"IW": {
  "version": 0x3,
  "share": {
    "names": ["VisibleChannels","OpenWeatherMap_APIKey","WeatherRefreshInterval","TextPrefixDayCurrent","TextPrefixDayNext","TextSun","TextClouds","TextRain","TextSnow"],
    "defaults": [1,"",3,"=","&gt;","Sonne",,"Regen XXXmm","Schnee XXXmm"]
    },
```

# Analyse und Lösungsideen
https://github.com/OpenKNX/OpenKNXproducer/blob/e4d7e8c7b00c18cd8b26fbe8ac924757373b5e43/ExtendedEtsSupport.cs#L164-L165
Die Prüfung erfasst nicht nur Platzhalter wie %C{1,4}(\*\d{1,4})?(+\d{1,4})?]%

## a) Schneller Fix
Genauere/Trennschärfere Prüfung (per RegEx?)

## b) Erweiterung mit Beseitigung Limitation in ConfigTransfer
Platzhalter erlauben und auch in ConfigTransfer verarbeiten. Erfordert weiteres Konzept für Kompatiblität und Umgang bei Abweichung von Quell/Ziel-Kanälen, oder Kanal-Neutralem Transfer-String.

**Comment by mumpf** [comment]
Hi, solved with 3.3.11
